// Mocks generated by Mockito 5.0.16 from annotations
// in mobile/test/homepage/domain/usecases/get_random_scan_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mobile/core/errors/failures.dart' as _i5;
import 'package:mobile/features/homepage/domain/entities/MangaInfo.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

import 'get_random_scan_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [TestHomePageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestHomePageRepository extends _i1.Mock
    implements _i3.TestHomePageRepository {
  MockTestHomePageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.MangaInfo>> getRandomScan() =>
      (super.noSuchMethod(Invocation.method(#getRandomScan, []),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.MangaInfo>>.value(
                  _FakeEither_0<_i5.Failure, _i6.MangaInfo>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.MangaInfo>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.MangaInfo>>>
      getListMangaPerSource(String? sourceName) => (super.noSuchMethod(
              Invocation.method(#getListMangaPerSource, [sourceName]),
              returnValue:
                  Future<_i2.Either<_i5.Failure, List<_i6.MangaInfo>>>.value(
                      _FakeEither_0<_i5.Failure, List<_i6.MangaInfo>>()))
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.MangaInfo>>>);
}
